-- First-party funnel events.
--
-- Privacy model, matching the rules in lib/funnel.js:
-- - No user_id and no email column. A signed-in event is a boolean, never an account reference, so
--   a funnel can be read without joining it back to a person.
-- - visitor_id is a random first-party UUID generated by the client, not derived from the account.
-- - properties is a small object of primitives; lib/funnel.js allowlists the keys before writing.
-- - No IP address, user agent, or device fingerprint is stored.
--
-- Writes go through the API using the service role, so there is deliberately no INSERT policy for
-- authenticated users: the browser cannot write events directly. Admins read counts through the API.
create table if not exists public.funnel_events (
  id bigserial primary key,
  event text not null check (event ~ '^[a-z][a-z0-9_]*$'),
  signed_in boolean not null default false,
  visitor_id text,
  properties jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists funnel_events_event_created_at_idx on public.funnel_events (event, created_at desc);

alter table public.funnel_events enable row level security;

-- No client INSERT/SELECT policies on purpose: events are written by the API (service role) and
-- read by the API for admins. RLS with no policies denies all direct client access.
